steps:
- id: 'build users service'
  name: gcr.io/cloud-builders/mvn
  args: ['install']
  dir: users

- id: 'build users service docker image'
  name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello-gcp-users', '.']
  dir: users/target/docker
  waitFor: ['build users service']

- id: 'install frontend dependencies'
  name: gcr.io/cloud-builders/npm
  args: ['install']
  dir: frontend

- id: 'prepare frontend docker image'
  name: gcr.io/cloud-builders/npm:node-10.10.0
  args: ['run', 'prepare-docker']
  dir: frontend
  waitFor: ['install frontend dependencies']

- id: 'build frontend docker image'
  name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello-gcp-frontend', '.']
  dir: frontend/docker
  waitFor: ['prepare frontend docker image']

- id: 'build gateway'
  name: gcr.io/cloud-builders/mvn
  args: ['install']
  dir: hello-gcp-gateway

- id: 'build gateway docker image'
  name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello-gcp-gateway', '.']
  dir: hello-gcp-gateway/target/docker
  waitFor: ['build gateway']

images: ['gcr.io/$PROJECT_ID/hello-gcp-frontend','gcr.io/$PROJECT_ID/hello-gcp-users','gcr.io/$PROJECT_ID/hello-gcp-gateway']