steps:
- name: gcr.io/cloud-builders/mvn
  args: ['install']
  dir: users

- name: gcr.io/cloud-builders/npm
  args: ['install']
  dir: frontend

- name: gcr.io/cloud-builders/npm:node-10.10.0
  args: ['run', 'prepare-docker']
  dir: frontend

- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello-gcp-frontend', '.']

  images: ['gcr.io/$PROJECT_ID/myimage']