server:
  use-forward-headers: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: 7979
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        descriptions: false

spring:
  application:
    name: hello-gcp-gateway

  cloud:
    gateway:
      routes:
      - id: ui
        uri: http://172.28.1.4/
        predicates:
        - Path=/app/**
        filters:
        - StripPrefix=1
      - id: users
        uri: http://172.28.1.3:8080/
        predicates:
        - Path=/users/**
