apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    application: gateway
spec:
  selector:
    application: gateway
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080