version: '3'

services:
  redis-master:
    image: redis
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    ports:
      - "6379:6379"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis_net:
          ipv4_address: 172.28.1.3

  redis-slave-one:
    image: redis
    volumes:
      - ./redis-slave-one/redis.conf:/usr/local/etc/redis/redis.conf:ro
    ports:
      - "6378:6379"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis_net:
          ipv4_address: 172.28.1.4

  redis-slave-two:
    image: redis
    volumes:
      - ./redis-slave-two/redis.conf:/usr/local/etc/redis/redis.conf:ro
    ports:
      - "6377:6379"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis_net:
          ipv4_address: 172.28.1.5

networks:
    redis_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16