apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
  labels:
    application: frontend
    version: "3"
spec:
  replicas: 1
  selector:
    matchLabels:
      application: frontend
  template:
    metadata:
      labels:
        application: frontend
        version: "1"
    spec:
      containers:
      - name: frontend
        image: gcr.io/siggi-example/hello-gcp-frontend
        ports:
        - containerPort: 80
          name: web
        resources:
          requests:
            memory: 32Mi
          limits:
            memory: 32Mi
        readinessProbe:
          httpGet:
            path: /app
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 5
