apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    application: frontend
spec:
  selector:
    application: frontend
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80